bucket: 'cct-ds-code-challenge-input-data'
key: 'cct-ds-code-challenge-input-data'
q1data: 'city-hex-polygons-8-10.geojson'
wind_data: 'https://www.capetown.gov.za/_layouts/OpenDataPortalHandler/DownloadHandler.ashx?DocumentName=Wind_direction_and_speed_2020.ods&DatasetDocument=https%3A%2F%2Fcityapps.capetown.gov.za%2Fsites%2Fopendatacatalog%2FDocuments%2FWind%2FWind_direction_and_speed_2020.ods'